"""refactor

Revision ID: 64f33b82eac4
Revises: 97b2edad7932
Create Date: 2025-01-02 19:33:21.281332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f33b82eac4'
down_revision = '97b2edad7932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['reading_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reading_progress')
    op.drop_table('book')
    op.drop_table('chapter')
    op.drop_table('verse')
    with op.batch_alter_table('reading_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_chapter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_chapter', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'chapter', ['current_chapter'], ['id'])
        batch_op.drop_column('streak')
        batch_op.drop_column('current_day')
        batch_op.drop_column('last_read_date')

    op.create_table('verse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('chapters', sa.INTEGER(), nullable=False),
    sa.Column('testament', sa.VARCHAR(length=20), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['reading_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('daily_reading')
    # ### end Alembic commands ###
